export const CURRENT_USER_NAME = "CURRENT_USER_NAME"
export const CURRENT_USER_AUTH = "CURRENT_USER_AUTH"
export const CURRENT_USER_TYPE = "CURRENT_USER_TYPE"

export const OTHER_USER_NAME = "OTHER_USER_NAME"

export const SELECTED_USER = "SELECTED_USER"
export const SELECTED_USER_INFO="SELECTED_USER_INFO"

export const CHAT_REQUEST = "CHAT_REQUEST"
export const CHAT_REQUESTOR = "CHAT_REQUESTOR"

export const VOICE_SCRIPT ="VOICE_SCRIPT"
export const LANGUAGE = "LANGUAGE"

export const INCOMING_CALL = 'INCOMING_CALL'

export const IS_RECORD = "IS_RECORD"
export const IS_CHAT ="IS_CHAT"

export const LAST_SEEN ="LAST_SEEN"
export const NEW_MSG_COUNT ='NEW_MSG_COUNT'
